victoire_core:
    widgets:
        Menu:
            class: "Victoire\\Widget\\MenuBundle\\Entity\\WidgetMenu"
            name: Menu
            #disable cache until https://github.com/Victoire/victoire/issues/507 is closed
            cache: false
