services:

    victoire_core.widget_menu_content_resolver:
        class: Victoire\Bundle\WidgetBundle\Resolver\BaseWidgetContentResolver
        tags:
            - { name: victoire_widget.widget_content_resolver, alias: Menu }
    #alias to the entity
    victoire.widget.menu:
        class: Victoire\Widget\MenuBundle\Entity\WidgetMenu

    victoire.widget.form.menu:
        class: Victoire\Widget\MenuBundle\Form\WidgetMenuType
        tags:
            - { name: form.type }

    victoire.form.menu:
        class: Victoire\Widget\MenuBundle\Form\MenuType
        tags:
            - { name: form.type }

